### ISSUE TITLE
建议重命名 pypi_requirements.txt

### ISSUE THREAD

**Issue by yzqzss** [Lyn4ever29/pipy_server#1]
*requirements.txt 会被 GitHub 识别为依赖，从而出现在被依赖项目的 Dependency graph 中。

现在至少上万个 repo 的 dependents 都被链接到了这个仓库……

可以重命名成 pypi-pkgs.dat 之类的名字

**Comment by ken-morel** [comment]
I do not understand what that means...., but I noticed this repository as one of the dependents of some of mine. I do not know why since it is listed neither in a setup.py or requirements.txt.

**Comment by ken-morel** [comment]
AH got it!:
> *requirements.txt will be recognized as a dependency by GitHub and will appear in the dependency > graph of the dependent project.
> Now at least tens of thousands of repo's dependencies are linked to this repository...
> You can rename it to something like pypi-pkgs.dat
